"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WhatsAppProfileVertical = void 0;
var WhatsAppProfileVertical;
(function (WhatsAppProfileVertical) {
    WhatsAppProfileVertical[WhatsAppProfileVertical["UNDEFINED"] = 0] = "UNDEFINED";
    WhatsAppProfileVertical[WhatsAppProfileVertical["OTHER"] = 1] = "OTHER";
    WhatsAppProfileVertical[WhatsAppProfileVertical["AUTO"] = 2] = "AUTO";
    WhatsAppProfileVertical[WhatsAppProfileVertical["BEAUTY"] = 3] = "BEAUTY";
    WhatsAppProfileVertical[WhatsAppProfileVertical["APPAREL"] = 4] = "APPAREL";
    WhatsAppProfileVertical[WhatsAppProfileVertical["EDU"] = 5] = "EDU";
    WhatsAppProfileVertical[WhatsAppProfileVertical["ENTERTAIN"] = 6] = "ENTERTAIN";
    WhatsAppProfileVertical[WhatsAppProfileVertical["EVENT_PLAN"] = 7] = "EVENT_PLAN";
    WhatsAppProfileVertical[WhatsAppProfileVertical["FINANCE"] = 8] = "FINANCE";
    WhatsAppProfileVertical[WhatsAppProfileVertical["GROCERY"] = 9] = "GROCERY";
    WhatsAppProfileVertical[WhatsAppProfileVertical["GOVT"] = 10] = "GOVT";
    WhatsAppProfileVertical[WhatsAppProfileVertical["HOTEL"] = 11] = "HOTEL";
    WhatsAppProfileVertical[WhatsAppProfileVertical["HEALTH"] = 12] = "HEALTH";
    WhatsAppProfileVertical[WhatsAppProfileVertical["NONPROFIT"] = 13] = "NONPROFIT";
    WhatsAppProfileVertical[WhatsAppProfileVertical["PROF_SERVICES"] = 14] = "PROF_SERVICES";
    WhatsAppProfileVertical[WhatsAppProfileVertical["RETAIL"] = 15] = "RETAIL";
    WhatsAppProfileVertical[WhatsAppProfileVertical["TRAVEL"] = 16] = "TRAVEL";
    WhatsAppProfileVertical[WhatsAppProfileVertical["RESTAURANT"] = 17] = "RESTAURANT";
    WhatsAppProfileVertical[WhatsAppProfileVertical["NOT_A_BIZ"] = 18] = "NOT_A_BIZ";
})(WhatsAppProfileVertical || (exports.WhatsAppProfileVertical = WhatsAppProfileVertical = {}));
